// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  escape: dynamic(() => import("./Escape")),
  hero: dynamic(() => import("./Hero")),
};
